# Generated by Django 3.0.5 on 2020-11-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('birthday', models.DateField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('relativeContact', models.CharField(blank=True, max_length=100)),
                ('pathologies', models.CharField(blank=True, max_length=100)),
                ('information', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(upload_to='Documents/')),
                ('otherFill', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField()),
                ('otherFill', models.CharField(blank=True, max_length=100)),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pill')),
            ],
        ),
    ]
